export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNLOAD_PRODUCTS'
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DOWNLOAD_PRODUCTS_SUCCESS'
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR'

export const OBTAIN_PRODUCT_DELETE = 'OBTAIN_PRODUCT_DELETE';
export const PRODUCT_REMOVED_SUCCESS = 'PRODUCT_REMOVED_SUCCESS';
export const PRODUCT_REMOVED_ERROR = 'PRODUCT_REMOVED_ERROR';

export const OBTAIN_PRODUCT_EDIT = 'OBTAIN_PRODUCT_EDIT';
export const START_EDITION_PRODUCT = 'START_EDITION_PRODUCT';
export const PRODUCT_EDITED_SUCCESS = 'PRODUCT_EDITED_SUCCESS';
export const PRODUCT_EDITED_ERROR = 'PRODUCT_EDITED_ERROR';
